### ISSUE TITLE
tunnel server offline: certificate has expired, retry 1s

### ISSUE THREAD

**Issue by s0ren** [berstend/puppeteer-extra#116]
When I try the first example from `https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-devtools`, I get:
`tunnel server offline: certificate has expired, retry 1s
Tunnel.js:64` 

Is that normal?
Can I update the certificate, somehow? Disable it?

Example SourceCode:
```javascript
const puppeteer = require('puppeteer-extra')
const devtools = require('puppeteer-extra-plugin-devtools')()
puppeteer.use(devtools)

puppeteer.launch().then(async browser => {
  const tunnel = await devtools.createTunnel(browser)
  console.log(tunnel.url) // => https://devtools-tunnel-sdoqqj95vg.localtunnel.me

  const page = await browser.newPage()
  await page.goto('https://www.google.com')
  await page.waitFor(60 * 1000)
  browser.close()
})
```

Best regards, and thank you

**Comment by jozsi** [comment]
It's an issue with the an underlying library, see: https://github.com/localtunnel/localtunnel/issues/332

Perhaps `puppeteer-extra-plugin-devtools` could accept an option to specify the host? Because, for the moment, you need to use either the non-https version of localtunnel, or a 3rd party server.

**Comment by berstend** [comment]
Yup, as @jozsi mentioned it's unfortunately an issue in the localtunnel project.

Will observe the situation for a moment and implement a host override if I find the time (PRs welcome). :)

**Comment by jozsi** [comment]
I'll give it a shot this week.

**Comment by jozsi** [comment]
Until #135 is merged, you can use the following in `package.json` to give it a try:
```
"puppeteer-extra-plugin-devtools": "jozsi/puppeteer-extra#puppeteer-extra-plugin-devtools-v2.2.9-gitpkg",
```

See the comment in #135 on how to work around the actual `tunnel server offline: certificate has expired, retry 1s` issue.

**Comment by pyrho** [comment]
localtunnel.me seems to be non-functional again, and its new maintainer has been AWOL too for a while.

I've quickly hacked around the code to rely on [ngrok](https://ngrok.com/) instead of localtunnel. The free plan is enough to get the same functionality except the ability to choose a subdomain/prefix (no signup to ngrok required btw).

I published a package like @jozsi (thanks btw I did not know about gitpkg) did  from my fork you can use the following as a drop-in replacement to the original package.
 
```
 "puppeteer-extra-plugin-devtools": "pyrho/puppeteer-extra#puppeteer-extra-plugin-devtools-v2.2.12-gitpkg",
```

Sorry for not submitting a proper PR for this, hopefully this can be of use to others too.

**Comment by berstend** [comment]
@jozsi's PR #135 has been merged, apologies for the delay. :-)

Closing this for now, please re-open in case there are further issues. Thanks!
