### ISSUE TITLE
Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"

### ISSUE THREAD

**Issue by JustinELRoberts** [berstend/puppeteer-extra#134]
I receive the following error when using puppeteer-extra with Electron on MacOS 10.15.2:

`Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"`

I am using the following function to open new browsers (note: it works fine with the regular puppeteer package):

```
async function openWindow(url)
{
	// Open a new window in headful mode
	const browser = await puppeteer.launch(
	{
		headless: false,
		defaultViewport: null,
	});

	// Create a reference to the first page
	const pages = await browser.pages();
	const page = pages[0];

	// Go to the url
	await page.goto(url);
}
```

I have tried running `npm install` again, but the error persisted.

**Comment by VanHop94** [comment]
Does anyone resolve this? please help

**Comment by JustinELRoberts** [comment]
I've yet to find what I consider a suitable solution :(. Some people say you can just specify the path to your chromium app with the `executablePath` option, but that isn't a very cross platform solution.

**Comment by VanHop94** [comment]
I just check log again and found that I missed puppeteer-extra module due to npm install not work, it require install manually, so I just install it and work well

**Comment by itsdarrylnorris** [comment]
You could do what @JustinELRoberts suggested. Or you could install puppeteer directly like `npm install  puppeteer --save`.

**Comment by bramvanhoutte** [comment]
I have the the same issue as @JustinELRoberts 😔

It works fine with regular `puppeteer`, but once launching it with `puppeteer-extra` it says:
"Could not find browser revision 756035. Run "npm install" or "yarn install" to download a browser binary."

The suggested solutions (run yarn install or add puppeteer directly) don't work for me. And I agree with @JustinELRoberts, specifying the chrome location isn't a solution.

@itsdarrylnorris would it be possible to re-open this issue, since a suitable solution/fix hasn't been found?
