### ISSUE TITLE
puppeteer-extra-plugin-block-resources: UnhandledPromiseRejectionWarning:

### ISSUE THREAD

**Issue by MarByteBeep** [berstend/puppeteer-extra#390]
When using the `puppeteer-extra-plugin-block-resources` plugin as advertised: 

```js
puppeteer.use(require('puppeteer-extra-plugin-block-resources')({
	blockedTypes: new Set(['image', 'stylesheet'])
}));
```

I get the following error:

```batch
UnhandledPromiseRejectionWarning: Error: Request is already handled!
    at Object.exports.assert (node_modules\puppeteer\lib\cjs\puppeteer\common\assert.js:26:15)
    at HTTPRequest.abort (node_modules\puppeteer\lib\cjs\puppeteer\common\HTTPRequest.js:317:21)
    at Plugin.onRequest (node_modules\puppeteer-extra-plugin-block-resources\index.js:101:34)
    at node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
    at Array.map (<anonymous>)
...
```

I've seen this error before when trying to set `page.setRequestInterception(value)` manually, and I'm guessing this plugin uses the same method. 

I'm using the plugin in conjunction with `puppeteer-extra-plugin-stealth` and `puppeteer-extra-plugin-adblocker`.

All plugins and Chromium are up to date.

**Comment by berstend** [comment]
@MarByteBeep having multiple plugins doing request interception is unfortunately problematic at the moment, due to the way this works in puppeteer/CDP: #364

I recommend using an alternative way of blocking resources for now: https://github.com/berstend/puppeteer-extra/wiki/Block-resources-without-request-interception

Closing in favor of #364 :-)

**Comment by MarByteBeep** [comment]
Thanks for the info!
