### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ali-habibzadeh** [berstend/puppeteer-extra#469]
Followed the instructions and did setup API key with 2captcha but I consistently get: ERROR_CAPTCHA_UNSOLVABLE

```
_vendor:'recaptcha'
error:'Error: 2captcha error: ERROR_CAPTCHA_UNSOLVABLE'
id:'6mmjx1c212lk'
provider:'2captcha'
requestAt:Fri Apr 02 2021 13:48:04 GMT+0100 (British Summer Time)
```

**Comment by brunogaspar** [comment]
You should put more effort on your bug reports, like adding a proper issue title and fill out the rest of the issue template, that's why it exists.

But either way, what versions are you using, what website is giving you this problem, does it happen for different websites with recaptcha? Have you reached out to 2captcha to determine if the culprit is on the code?

For the `ERROR_CAPTCHA_UNSOLVABLE`, 2captcha says the following on their website:

```
We are unable to solve your captcha - three of our workers were unable solve it or we didn't get an answer within 90 seconds (300 seconds for reCAPTCHA V2).
We will not charge you for that request.
```

So without any other information, it can be an issue on either end 🤷‍♂️

**Comment by berstend** [comment]
From that I've heard 2captcha had a temporary API issue so this might be resolved. Other than that your issue is the reason we have (and enforce) using our template, if you don't even bother writing a headline I won't bother helping you. :-)
