### ISSUE TITLE
puppeteer-extra-plugin-stelth onBrowser typing throws error TS2416

### ISSUE THREAD

**Issue by critocrito** [berstend/puppeteer-extra#87]
Hey,

I import `puppeteer-extra-plugin-stealth` into a typescript project and when type-checking I get the following:

```
$ tsc --noEmit
node_modules/puppeteer-extra-plugin-stealth/index.d.ts:110:5 - error TS2416: Property 'onBrowser' in type 'StealthPlugin' is not assignable to the same property in base type 'PuppeteerExtraPlugin'.
  Type '(browser: any) => void' is not assignable to type '(browser: Browser, opts: any) => Promise<void>'.
    Type 'void' is not assignable to type 'Promise<void>'.

110     onBrowser(browser: any): void;
```

I locally changed the line to `onBrowser(browser: any, opts: any): Promise<void>;` which makes it type check. I'm new to Typescript and am not sure how to import `Browser` into a declaration file in order to get rid of the `any` and send a proper pull request.

**Comment by berstend** [comment]
Hey @critocrito no problem - thanks for asking :)

> Type 'void' is not assignable to type 'Promise<void>'.

That just means that the signature expects a promised to be returned, you could either do that or (more elegantly) make it an `async` method:

```ts
  async onBrowser() {
    // foo
  }
```

Next step is that you probably want to use the `browser` parameter in a typed way:
![image](https://user-images.githubusercontent.com/1368633/70219292-dd864280-1744-11ea-907f-155369ce46a2.png)

In order to that you'd need to `yarn add @types/puppeteer` and import the Browser definition:

```ts
import { Browser } from "puppeteer"
```

And by using `browser: Browser` it's type safe:

![image](https://user-images.githubusercontent.com/1368633/70219508-3f46ac80-1745-11ea-987e-a1d16c46918b.png)

Here's the full code:

```ts
import { PuppeteerExtraPlugin } from "puppeteer-extra-plugin"

import { Browser } from "puppeteer"

export class PuppeteerExtraPluginRecaptcha extends PuppeteerExtraPlugin {
  constructor() {
    super()
    this.debug("Initialized", this.opts)
  }

  get name() {
    return "typescript-demo-plugin"
  }

  async onBrowser(browser: Browser) {
    // foo
  }
}
```

The `tsconfig.json` I can recommend can be [found here](https://github.com/berstend/puppeteer-extra/wiki/TypeScript-usage).

A good reference for developing a Plugin in TypeScript might be the [Stealth](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth) and [Adblocker](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-adblocker) plugin (both written in TypeScript, I recommend using their package.json with scripts as a template as well).

Let me know if you have further questions or if it makes sense to upload a small hello-world plugin in Typescript. :)

**Comment by berstend** [comment]
PS: I recommend using VSCode as an editor for TypeScript project, as it will show you Typescript errors directly in your code (no need for running `tsc --noEmit`). :)

**Comment by berstend** [comment]
Ah, I maybe misread your first comment - are you trying to add a new evasion to the the Stealth plugin? :)

I read your comment as you were trying to create a new plugin from scratch.

In case you're trying to add a new evasion plugin to Stealth: I'd recommend using plain JavaScript for that as the stealth plugin is written in good old JavaScript. :)

**Comment by berstend** [comment]
Oh wait, I actually had a bug in the d.ts file of the stealth plugin (it's generated from JSDoc so not perfect).

I just fixed it and published it as `puppeteer-extra-plugin-stealth@2.4.4` - please try again what you were doing with the new version :)

The fix was this: https://github.com/berstend/puppeteer-extra/commit/f0e4df45ad255ce62a01c43bf1e17100b256f3e6

**Comment by critocrito** [comment]
Hey @berstend,

I just wrote a response the last ten minutes pointing out line in the `index.d.ts` but you were quicker. And apologies that I expressed my issue so poorly. 

Your fix solved my issue. Thanks so much for your quick and elaborate reply, and the prompt new release.

**Comment by berstend** [comment]
@critocrito no problem, happy to help. Thanks for the update that the issue is fixed :)
